public class InadequateCatchLog {
	 public static void anotherMainFunction(String[] args) {
	        try {
	        	
	        }
	        catch(ArrayIndexOutOfBoundsException e) {
	        	System.out.println("array index out of bounds exception");
	        }
	        catch(ArrayIndexOutOfBoundsException e) {
	        	System.out.println("array index out of bounds exception");
	        }
	    }
	    public static void another(String[] args) {

	    try {
	    	
	    }
	    catch(ArrayIndexOutOfBoundsException e) {
	    	System.out.println();
	    }}
}